### ISSUE TITLE
name 'CONFIG' is not defined

### ISSUE THREAD

**Issue by roymina** [ekatraone/Alpaca-style-Dataset-Generator#2]
errors when run ` python src/main.py --num_examples 1000` :
```bash
Loading input data...
Loading input files:   0%|                                                   | 0/1 [00:00<?, ?file/s]
Traceback (most recent call last):
  File "D:\github_clones\Alpaca-style-Dataset-Generator\src\main.py", line 34, in <module>
    main()
  File "D:\github_clones\Alpaca-style-Dataset-Generator\src\main.py", line 10, in main
    input_texts = load_input_data(CONFIG['input_folder'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github_clones\Alpaca-style-Dataset-Generator\src\data_loader.py", line 20, in load_input_data
    with ThreadPoolExecutor(max_workers=CONFIG['max_workers']) as executor:
                                        ^^^^^^
NameError: name 'CONFIG' is not defined
```

**Comment by bbeartheancient** [comment]
add "from config import CONFIG" to the top of data_loader.py
